# .streamlit/config.toml

[theme]
base                      = "light"
primaryColor              = "#0F766E"
backgroundColor           = "#FFFFFF"
secondaryBackgroundColor  = "#F6F7F9"
textColor                 = "#111827"
font                      = "sans serif"

[server]
port                 = 8501
enableCORS           = false
enableXsrfProtection = true
fileWatcherType      = "poll"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[client]
showErrorDetails = true
toolbarMode      = "minimal"
